os: linux
dist: trusty
sudo: true
language: c
git:
  depth: 3
compiler:
  - gcc
install: false
script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-5.4 -y
  - mkdir build && cd build
  - cmake ..
  - make
  - cd ../test
  - ./test_all.sh
notifications:
  email: false
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    on_success: change
    on_failure: always
    on_cancel: never
    on_error: always
