os: linux
dist: trusty
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
language: c
git:
  depth: 3
compiler:
  - gcc
install: false
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - mkdir build && cd build
  - cmake ..
  - make
  - cd ../test
  - ./test_all.sh
notifications:
  email: false